[package]
name = "searching"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = {version = "1.0.144", features = ["derive"] }
reqwest = { version = "0.12", features = ["json", "blocking"] }
bytes = "1"